---
name: ts-snippets TypeScript-Workflow

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  qualify_code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: npm ci
        run: npm ci

      # setup eslint config file locally first:
      # npm init @eslint/config
      - name: Run ESLint
        run: npx eslint --ext .ts src/
